// Code generated by go generate; DO NOT EDIT.
// This file was generated by genenum.go

package main

var namesHTTPCode = map[HTTPCode]string{
	400: "BadRequest",
	401: "Unauthorized",
	403: "Forbidden",
	404: "NotFound",
	429: "TooManyRequests", // DDOS alert, call admins!
	500: "Internal",
}

func (v HTTPCode) String() string {
	return namesHTTPCode[v]
}
